name: puzzle_game
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.6+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.5
  flutter_riverpod: ^2.5.1
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  hugeicons: ^1.1.1
  iconsax: ^0.0.8
  kartal: ^4.2.0
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.14.4
  flame: ^1.19.0
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/new_app_icon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 800
